# Generated by Django 3.2.7 on 2021-09-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='scholl_name',
            new_name='school_name',
        ),
    ]
