# Generated by Django 3.2.7 on 2021-09-25 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_alter_school_sch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sch_name1',
            field=models.CharField(default=django.utils.timezone.now, max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='sch_name',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('sch_name', 'sch_name1')},
        ),
    ]
